spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: algo
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    password: ssafyalgo!1@
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update