version: '3.2'
services:
  sample:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "5174:5174"
    container_name: front
    restart: always
    image: ssafy10b108/fe:240214-1232